# Generated by Django 3.2.5 on 2022-01-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='orig_pid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='orig_pid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
