# Generated by Django 4.2.14 on 2024-12-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimages',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='download_date',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='species',
        ),
        migrations.AddField(
            model_name='hybrid',
            name='pollen_accid',
            field=models.ForeignKey(blank=True, db_column='pollen_accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othpollen_accid', to='other.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='seed_accid',
            field=models.ForeignKey(blank=True, db_column='seed_accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othseed_accid', to='other.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='spcimages',
            name='accid',
            field=models.ForeignKey(blank=True, db_column='accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othimgaccid', to='other.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='spcimages',
            name='base_pid',
            field=models.ForeignKey(blank=True, db_column='base_pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othimgbase_pid', to='other.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='species',
            name='accid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='base_pid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
