# Generated by Django 3.0.9 on 2021-01-27 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('core', '0007_family_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(db_column='family', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolfamily', to='core.Family'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='subfamily',
            field=models.ForeignKey(db_column='subfamily', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolsubfamily', to='core.Subfamily'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='subtribe',
            field=models.ForeignKey(db_column='subtribe', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolsubtribe', to='core.Subtribe'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='tribe',
            field=models.ForeignKey(db_column='tribe', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pooltribe', to='core.Tribe'),
        ),
        migrations.AlterField(
            model_name='spcimages',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolapproved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spcimages',
            name='author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolspcauthor', to='accounts.Photographer'),
        ),
        migrations.AlterField(
            model_name='spcimages',
            name='family',
            field=models.ForeignKey(db_column='family', on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolspcfamily', to='core.Family'),
        ),
        migrations.AlterField(
            model_name='spcimages',
            name='gen',
            field=models.ForeignKey(blank=True, db_column='gen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolspcgen', to='other.Genus'),
        ),
        migrations.AlterField(
            model_name='spcimages',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolpid', to='other.Species'),
        ),
        migrations.AlterField(
            model_name='spcimages',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pooluser_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='species',
            name='gen',
            field=models.ForeignKey(db_column='gen', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolgen', to='other.Genus'),
        ),
    ]
