# Generated by Django 4.2.14 on 2024-09-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_genusstat_speciesstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='notepad',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_hyb_with_image',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_hybimage',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_hybrid',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_hybrid_synonym',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_hybrid_total',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_spc_with_image',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_spcimage',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_species',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_species_synonym',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_species_total',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='num_synonym',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='pct_hyb_with_image',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='pct_spc_with_image',
        ),
    ]
