# Generated by Django 3.0.9 on 2021-01-27 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('other', '0002_auto_20210127_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hybrid',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='other.Species')),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('genus', models.CharField(blank=True, max_length=50, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('infraspr', models.CharField(blank=True, max_length=20, null=True)),
                ('is_hybrid', models.CharField(blank=True, max_length=5, null=True)),
                ('infraspe', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('seed_genus', models.CharField(blank=True, max_length=50, null=True)),
                ('seed_species', models.CharField(blank=True, max_length=50, null=True)),
                ('seed_type', models.CharField(blank=True, max_length=10, null=True)),
                ('pollen_genus', models.CharField(blank=True, max_length=50, null=True)),
                ('pollen_species', models.CharField(blank=True, max_length=50, null=True)),
                ('pollen_type', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('originator', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('culture', models.TextField(blank=True, null=True)),
                ('etymology', models.TextField(blank=True, null=True)),
                ('num_image', models.IntegerField(blank=True, null=True)),
                ('num_ancestor', models.IntegerField(blank=True, null=True)),
                ('num_species_ancestor', models.IntegerField(blank=True, null=True)),
                ('num_descendant', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('gen', models.ForeignKey(db_column='gen', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othhybgen', to='other.Genus')),
                ('pollen_gen', models.ForeignKey(db_column='pollgen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othpollgen', to='other.Genus')),
                ('pollen_id', models.ForeignKey(blank=True, db_column='pollen_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othpollen_id', to='other.Species')),
                ('seed_gen', models.ForeignKey(db_column='seedgen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othseedgen', to='other.Genus')),
                ('seed_id', models.ForeignKey(blank=True, db_column='seed_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othseed_id', to='other.Species')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othuser_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
