# Generated by Django 3.2.13 on 2022-05-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_accepted_introduced'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSpecies',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('genus', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='species',
            name='infraspe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='infraspr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('registered', 'registered'), ('nonregistered', 'nonregistered'), ('unplaced', 'unplaced'), ('published', 'published'), ('trade', 'trade'), ('synonym', 'synonym')], default='', max_length=20),
        ),
    ]
