# Generated by Django 4.2.14 on 2024-09-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_remove_genus_notepad_remove_genus_num_hyb_with_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='notepad',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_ancestor',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_descendant',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_dir_descendant',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_image',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_species_ancestor',
        ),
    ]
