# Generated by Django 3.2.5 on 2021-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_auto_20210710_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='pid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='pid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
