# Generated by Django 3.1.6 on 2021-03-28 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_genus_is_succulent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('spid', models.OneToOneField(db_column='spid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cacspid', serialize=False, to='other.species')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cacaccid', to='other.species', verbose_name='accepted genus')),
            ],
        ),
    ]
