# Generated by Django 4.2.14 on 2025-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_remove_genusstat_num_hyb_with_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesstat',
            name='num_image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
