# Generated by Django 3.2.13 on 2022-05-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_auto_20220531_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='genus',
            name='orig_pid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='species',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
