# Generated by Django 3.2.13 on 2022-05-31 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_subfamily_family'),
        ('other', '0005_auto_20220531_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, db_column='family', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='otfamily', to='core.family'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='subfamily',
            field=models.ForeignKey(blank=True, db_column='subfamily', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolsubfamily', to='core.subfamily'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='subtribe',
            field=models.ForeignKey(blank=True, db_column='subtribe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poolsubtribe', to='core.subtribe'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='tribe',
            field=models.ForeignKey(blank=True, db_column='tribe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pooltribe', to='core.tribe'),
        ),
    ]
