# Generated by Django 3.1.6 on 2021-03-28 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('other', '0006_auto_20210328_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='other.species')),
                ('genus', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('infraspr', models.CharField(max_length=20, null=True)),
                ('infraspe', models.CharField(max_length=50, null=True)),
                ('distribution', models.TextField(blank=True)),
                ('is_type', models.BooleanField(default=False, null=True)),
                ('physiology', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('common_name', models.CharField(blank=True, max_length=100, null=True)),
                ('local_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bloom_month', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fragrance', models.CharField(blank=True, max_length=50, null=True)),
                ('altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('etymology', models.TextField(blank=True, null=True)),
                ('culture', models.TextField(blank=True, null=True)),
                ('subgenus', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('subsection', models.CharField(blank=True, max_length=50, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('num_image', models.IntegerField(blank=True, null=True)),
                ('num_descendant', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('gen', models.ForeignKey(blank=True, db_column='gen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othgen_id', to='other.genus')),
                ('operator', models.ForeignKey(db_column='operator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='othoperator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
