# Generated by Django 3.2.13 on 2022-05-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0006_auto_20220531_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='abrev',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='genus',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='genus',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
