# Generated by Django 3.1.6 on 2021-03-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0007_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gensyn',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='other.genus')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_id', to='other.genus', verbose_name='genus')),
            ],
        ),
    ]
