# Generated by Django 3.2.13 on 2022-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0007_auto_20220531_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='orig_pid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='source',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
