# Generated by Django 3.2.13 on 2022-05-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0008_auto_20220531_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
