# Generated by Django 3.2.15 on 2024-06-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_auto_20240305_0250'),
        ('other', '0009_auto_20240506_1923'),
    ]

    operations = [
    ]
