# Generated by Django 3.2.13 on 2022-05-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0009_alter_species_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
