# Generated by Django 3.2.15 on 2024-06-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0011_delete_testspecies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='family',
        ),
    ]
