# Generated by Django 3.1.6 on 2021-04-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210329_1547'),
        ('other', '0011_genusrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='continent_id',
            field=models.ForeignKey(blank=True, db_column='continent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nat_continent_id', to='core.continent'),
        ),
    ]
