# Generated by Django 3.2.15 on 2022-10-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0011_alter_accepted_common_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.CharField(blank=True, max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
