# Generated by Django 3.2.15 on 2022-10-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0012_distlocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistLocation',
            new_name='Location',
        ),
    ]
