# Generated by Django 3.1.6 on 2021-04-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0012_distribution_continent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='dist_code',
        ),
        migrations.AddField(
            model_name='distribution',
            name='distribution',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='orig_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
