# Generated by Django 3.2.15 on 2022-10-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0014_distlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distlocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
