# Generated by Django 3.1.6 on 2021-04-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0014_auto_20210406_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_succulent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
