# Generated by Django 3.2.15 on 2022-10-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0017_alter_distlocation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distlocation',
            name='dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other.location'),
        ),
    ]
