# Generated by Django 3.2.15 on 2022-10-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0018_alter_distlocation_dist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistLocation',
        ),
    ]
