# Generated by Django 3.1.6 on 2021-04-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0020_species_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='binomial',
        ),
    ]
