# Generated by Django 3.2.15 on 2022-10-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0020_distlocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distlocation',
            unique_together=set(),
        ),
    ]
