# Generated by Django 3.1 on 2021-04-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0022_remove_genus_alliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_carnivorous',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
