# Generated by Django 3.2.15 on 2022-10-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0022_distlocation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distlocation',
            name='name',
        ),
        migrations.AlterField(
            model_name='distlocation',
            name='dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_id', to='other.location'),
        ),
    ]
