# Generated by Django 3.1 on 2021-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0023_species_is_carnivorous'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='is_carnivorous',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
