# Generated by Django 3.2.15 on 2022-10-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0023_auto_20221024_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistLocation',
        ),
    ]
