# Generated by Django 3.2.15 on 2022-10-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0024_delete_distlocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='continent_id',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='localregion_code',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='localregion_id',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='orig_code',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='source',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='subregion_code',
        ),
    ]
