# Generated by Django 3.1 on 2021-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0024_genus_is_carnivorous'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='is_extinct',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
