# Generated by Django 3.1 on 2021-05-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0025_genus_is_extinct'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_parasite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
