# Generated by Django 3.2.15 on 2022-10-25 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0027_auto_20221025_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='dist',
            field=models.ForeignKey(db_column='dist', default='', on_delete=django.db.models.deletion.CASCADE, to='other.location'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='pid',
            field=models.ForeignKey(db_column='pid', default='', on_delete=django.db.models.deletion.CASCADE, related_name='othdist_pid', to='other.species'),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together={('pid', 'dist')},
        ),
    ]
