# Generated by Django 3.2.15 on 2022-10-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0028_auto_20221025_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
