# Generated by Django 3.2.15 on 2022-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0030_auto_20221103_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='spcimages',
            name='binomial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
