# Generated by Django 3.2.15 on 2022-12-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0034_auto_20221201_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybrid',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='infraspe',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='infraspr',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='source',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='species',
        ),
    ]
