# Generated by Django 3.2.15 on 2022-12-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0035_auto_20221201_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='history',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='infraspe',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='infraspr',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='species',
        ),
    ]
