# Generated by Django 3.2.15 on 2023-03-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0036_auto_20221201_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='dist',
            field=models.ForeignKey(db_column='dist', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='other.location'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='pid',
            field=models.ForeignKey(db_column='pid', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='othdist_pid', to='other.species'),
        ),
    ]
