# Generated by Django 3.0.9 on 2021-01-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoLoc',
        ),
    ]
