# Generated by Django 3.0.9 on 2021-01-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210106_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
