# Generated by Django 3.0.9 on 2021-01-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_family_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfamily',
            name='num_genus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subtribe',
            name='num_genus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='num_genus',
            field=models.IntegerField(null=True),
        ),
    ]
