# Generated by Django 3.0.9 on 2021-01-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210117_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='source',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
