# Generated by Django 3.0.9 on 2021-03-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_taxonomy_taxtree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxtree',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='taxtree',
            name='taxon',
        ),
        migrations.DeleteModel(
            name='Taxonomy',
        ),
        migrations.DeleteModel(
            name='TaxTree',
        ),
    ]
