# Generated by Django 3.0.9 on 2021-03-20 19:24

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210320_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxon', models.CharField(db_column='taxon', default='', max_length=50, primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Taxonomy')),
            ],
        ),
    ]
