# Generated by Django 3.0.9 on 2021-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
