# Generated by Django 3.0.9 on 2021-03-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_taxonomy_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='parent_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
