# Generated by Django 3.0.9 on 2021-03-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210320_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
