# Generated by Django 3.1.6 on 2021-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_family_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='num_image',
            field=models.IntegerField(null=True),
        ),
    ]
