# Generated by Django 3.1.6 on 2021-03-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_family_num_hybimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='num_image',
            new_name='num_spcimage',
        ),
    ]
