# Generated by Django 3.2.2 on 2021-07-04 07:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210329_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon', models.CharField(db_column='taxon', default='', max_length=50)),
                ('parent_name', models.CharField(max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.IntegerField(null=True)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.taxonomy1')),
            ],
        ),
    ]
