# Generated by Django 3.2.2 on 2021-07-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210704_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ['taxon', 'parent_name']},
        ),
        migrations.AlterUniqueTogether(
            name='taxonomy',
            unique_together={('taxon', 'parent_name')},
        ),
    ]
