# Generated by Django 3.2.2 on 2021-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210704_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='common_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
