# Generated by Django 3.2.5 on 2021-11-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20211109_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='num_hybimage',
        ),
        migrations.RemoveField(
            model_name='family',
            name='num_spcimage',
        ),
    ]
