# Generated by Django 3.2.5 on 2022-01-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_family_orig_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('registered', 'registered'), ('nonregistered', 'nonregistered'), ('unplaced', 'unplaced'), ('published', 'published'), ('trade', 'trade')], default='', max_length=20),
        ),
    ]
