# Generated by Django 3.2.13 on 2022-05-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_family_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfamily',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtribe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
