# Generated by Django 3.2.13 on 2022-05-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220521_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfamily',
            name='family',
            field=models.ForeignKey(blank=True, db_column='family', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='core.family'),
        ),
    ]
