# Generated by Django 3.2.15 on 2022-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220620_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='orig_pid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
