# Generated by Django 4.2.14 on 2024-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='pollen_binomial',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='seed_binomial',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
