# Generated by Django 3.2.15 on 2024-03-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE orchidaceae_species ADD FULLTEXT(binomial, author)',
            reverse_sql='ALTER TABLE orchidaceae_species DROP INDEX binomial_author_fulltext'
        ),
    ]
