# Generated by Django 3.0.9 on 2021-02-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgenus',
            name='pid',
        ),
        migrations.AlterField(
            model_name='species',
            name='pid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Grexrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('relation', models.CharField(choices=[('direct', 'direct'), ('reverse', 'reverse')], default='', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('pid1', models.ForeignKey(db_column='pid1', on_delete=django.db.models.deletion.CASCADE, related_name='pid1', to='orchidaceae.Hybrid')),
                ('pid2', models.ForeignKey(db_column='pid2', on_delete=django.db.models.deletion.CASCADE, related_name='pid2', to='orchidaceae.Hybrid')),
            ],
            options={
                'unique_together': {('pid1', 'pid2')},
            },
        ),
    ]
