# Generated by Django 3.2.2 on 2021-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='conservation_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
