# Generated by Django 4.2.14 on 2024-09-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted',
            name='num_descendant',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='num_image',
        ),
    ]
