# Generated by Django 3.2.2 on 2021-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0002_species_conservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='is_parasite',
            new_name='is_parasitic',
        ),
        migrations.AddField(
            model_name='genus',
            name='is_parasitic',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
