# Generated by Django 4.2.14 on 2024-12-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0002_hybrid_pollen_binomial_hybrid_seed_binomial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybimages',
            name='pid',
            field=models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hybimgpid', to='orchidaceae.species', verbose_name='grex'),
        ),
    ]
