# Generated by Django 4.2.14 on 2024-09-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0002_remove_accepted_num_descendant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybrid',
            name='num_ancestor',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='num_descendant',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='num_image',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='num_species_ancestor',
        ),
    ]
