# Generated by Django 3.2.2 on 2021-08-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0003_auto_20210710_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('alid', models.ForeignKey(blank=True, db_column='alid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alid', to='orchidaceae.genus')),
                ('gen', models.ForeignKey(blank=True, db_column='gen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algen', to='orchidaceae.genus')),
            ],
            options={
                'ordering': ['alliance'],
                'unique_together': {('alid', 'gen')},
            },
        ),
    ]
