# Generated by Django 4.2.14 on 2024-12-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0003_alter_hybimages_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybimages',
            name='binomial',
        ),
    ]
