# Generated by Django 3.1.6 on 2021-03-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0003_genus_is_succulent'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
