# Generated by Django 4.2.14 on 2024-12-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0004_remove_hybimages_binomial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimages',
            name='binomial',
        ),
    ]
