# Generated by Django 3.2.5 on 2021-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0004_alliance'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='species',
        #     name='pid',
        #     field=models.BigAutoField(primary_key=True, serialize=False),
        # ),
    ]
