# Generated by Django 3.2.15 on 2024-04-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0004_auto_20240427_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='cit_status',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='section',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='series',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='species',
            name='cit_status',
        ),
        migrations.RemoveField(
            model_name='species',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='subgenus',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='citation',
        ),
    ]
