# Generated by Django 3.2.5 on 2021-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0005_alter_species_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='pid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
