# Generated by Django 3.1.6 on 2021-04-17 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0005_auto_20210329_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gensyn',
            name='abrev',
        ),
        migrations.RemoveField(
            model_name='gensyn',
            name='acc_author',
        ),
        migrations.RemoveField(
            model_name='gensyn',
            name='acc_year',
        ),
        migrations.RemoveField(
            model_name='gensyn',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='gensyn',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gensyn',
            name='source',
        ),
        migrations.RemoveField(
            model_name='gensyn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gensyn',
            name='type',
        ),
    ]
