# Generated by Django 4.2.14 on 2024-12-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0006_donation_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybimages',
            name='accid',
            field=models.ForeignKey(blank=True, db_column='accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hybimgaccid', to='orchidaceae.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='pollen_accid',
            field=models.ForeignKey(blank=True, db_column='pollen_accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orpollen_accid', to='orchidaceae.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='seed_accid',
            field=models.ForeignKey(blank=True, db_column='seed_accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orseed_accid', to='orchidaceae.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='spcimages',
            name='accid',
            field=models.ForeignKey(blank=True, db_column='accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spcimgaccid', to='orchidaceae.species', verbose_name='grex'),
        ),
    ]
