# Generated by Django 3.1.6 on 2021-04-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0006_auto_20210417_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='binomial',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
