# Generated by Django 3.2.15 on 2024-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0006_auto_20240502_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='binomial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hybimages',
            name='binomial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spcimages',
            name='binomial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='binomial',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='binomial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
