# Generated by Django 3.2.5 on 2022-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0006_alter_species_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='orig_pid',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='orig_pid',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
