# Generated by Django 4.2.14 on 2024-12-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0007_hybimages_accid_hybrid_pollen_accid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybimages',
            name='spid',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='spid',
        ),
    ]
