# Generated by Django 3.2.15 on 2024-05-09 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0008_auto_20240509_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gensyn',
            name='acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accgensyn', to='orchidaceae.genus', verbose_name='genus'),
        ),
        migrations.AlterField(
            model_name='gensyn',
            name='pid',
            field=models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gensyn', serialize=False, to='orchidaceae.genus'),
        ),
    ]
