# Generated by Django 3.2.15 on 2023-01-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0008_auto_20220106_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spcimages',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orpid', to='orchidaceae.species'),
        ),
        migrations.AlterField(
            model_name='spcimghistory',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, related_name='or1pid', to='orchidaceae.species'),
        ),
        migrations.AlterField(
            model_name='specieshistory',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, related_name='orpid3', to='orchidaceae.species'),
        ),
    ]
