# Generated by Django 4.2.14 on 2024-12-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0008_remove_hybimages_spid_remove_spcimages_spid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybimages',
            name='base_pid',
            field=models.ForeignKey(blank=True, db_column='base_pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hybimgbase_pid', to='orchidaceae.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='spcimages',
            name='base_pid',
            field=models.ForeignKey(blank=True, db_column='base_pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spcimgbase_pid', to='orchidaceae.species', verbose_name='grex'),
        ),
    ]
