# Generated by Django 3.2.15 on 2023-03-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0009_auto_20230123_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordist_pid', to='orchidaceae.species'),
        ),
    ]
