# Generated by Django 4.2.14 on 2024-12-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0009_hybimages_base_pid_spcimages_base_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='base_pid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
