# Generated by Django 3.2.15 on 2024-05-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0010_auto_20240512_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synonym',
            name='binomial',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='sbinomial',
        ),
        migrations.AddField(
            model_name='synonym',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='infraspe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='infraspr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='sgen',
            field=models.ForeignKey(blank=True, db_column='sgen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orsgen', to='orchidaceae.genus'),
        ),
        migrations.AddField(
            model_name='synonym',
            name='sgenus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='sinfraspe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='sinfraspr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='sis_hybrid',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='sspecies',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='syear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
