# Generated by Django 4.2.14 on 2024-12-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0010_species_base_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='accid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
