# Generated by Django 3.2.15 on 2024-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0011_auto_20240512_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='binomial',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='synonym',
            name='sbinomial',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
