# Generated by Django 3.1 on 2021-05-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0011_remove_genus_binomial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alliance',
        ),
    ]
