# Generated by Django 4.2.14 on 2024-12-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0011_species_accid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybimages',
            name='binomial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spcimages',
            name='binomial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
