# Generated by Django 4.2.14 on 2025-05-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0012_hybimages_binomial_spcimages_binomial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimages',
            name='image_file_path',
        ),
    ]
