# Generated by Django 3.1 on 2021-05-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0012_delete_alliance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenusTree',
        ),
    ]
