# Generated by Django 3.2.15 on 2024-05-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0013_remove_synonym_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synonym',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='description',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='infraspe',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='infraspr',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='sgen',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='sgenus',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='sinfraspe',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='sinfraspr',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='sis_hybrid',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='sspecies',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='syear',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='type',
        ),
    ]
