# Generated by Django 4.2.14 on 2025-05-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0013_remove_spcimages_image_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybimages',
            name='image_file_path',
        ),
    ]
