# Generated by Django 3.1 on 2021-05-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0013_delete_genustree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infragenhybrid',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='infragenrelation',
            name='gen',
        ),
        migrations.RemoveField(
            model_name='infragenrelation',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Infragen',
        ),
        migrations.DeleteModel(
            name='InfragenHybrid',
        ),
        migrations.DeleteModel(
            name='Infragenrelation',
        ),
    ]
