# Generated by Django 4.2.14 on 2025-05-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0014_remove_hybimages_image_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='genusstat',
            name='best_hybrid_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='genusstat',
            name='best_species_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
