# Generated by Django 4.2.14 on 2024-08-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0015_auto_20240512_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='gen',
            field=models.ForeignKey(db_column='gen', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='or6gen', to='orchidaceae.genus'),
        ),
    ]
