# Generated by Django 4.2.14 on 2025-05-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0015_genusstat_best_hybrid_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genusstat',
            old_name='best_hybrid_image',
            new_name='best_image',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='best_species_image',
        ),
    ]
