# Generated by Django 4.2.14 on 2025-05-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0016_rename_best_hybrid_image_genusstat_best_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesstat',
            name='best_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
