# Generated by Django 4.2.14 on 2024-08-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0017_genusstat_speciesstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genusstat',
            name='pid',
            field=models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='genusstat', serialize=False, to='orchidaceae.genus'),
        ),
        migrations.AlterField(
            model_name='speciesstat',
            name='pid',
            field=models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='speciesstat', serialize=False, to='orchidaceae.species'),
        ),
    ]
