# Generated by Django 4.2.14 on 2025-05-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0017_speciesstat_best_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genusstat',
            name='best_image_pid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
