# Generated by Django 4.2.14 on 2025-05-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0018_genusstat_best_image_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesstat',
            name='num_image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
