# Generated by Django 4.2.14 on 2025-06-19 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('orchidaceae', '0019_alter_speciesstat_num_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='subregion_code',
            new_name='subregion_id',
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together={('pid', 'region_id', 'subregion_id')},
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='dist_code',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='dist_status',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='localregion_code',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='localregion_id',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='orig_code',
        ),
    ]
