# Generated by Django 4.2.14 on 2024-08-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0019_remove_genus_notepad_remove_genus_num_hyb_with_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybimages',
            name='binomial',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='binomial',
        ),
    ]
