# Generated by Django 4.2.14 on 2025-06-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('orchidaceae', '0020_rename_subregion_code_distribution_subregion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='distributions', to='orchidaceae.species'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='subregion_id',
            field=models.ForeignKey(db_column='subregion_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orsubregion_id', to='common.subregion'),
        ),
    ]
