# Generated by Django 4.2.14 on 2025-07-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0021_alter_distribution_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='regions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
