# Generated by Django 4.2.14 on 2025-07-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0022_accepted_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='regions',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
