# Generated by Django 4.2.14 on 2025-10-01 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orchidaceae', '0024_species_common_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_flags', to=settings.AUTH_USER_MODEL)),
                ('hyb_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='orchidaceae.hybimages')),
                ('spc_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='orchidaceae.spcimages')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='orchidaceae.species')),
            ],
        ),
        migrations.RemoveField(
            model_name='spcimghistory',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='spcimghistory',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='HybImgHistory',
        ),
        migrations.DeleteModel(
            name='SpcImgHistory',
        ),
        migrations.AddConstraint(
            model_name='imageflag',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('spc_image__isnull', False), ('hyb_image__isnull', True)), models.Q(('spc_image__isnull', True), ('hyb_image__isnull', False)), _connector='OR'), name='imageflag_exactly_one_fk'),
        ),
        migrations.AddConstraint(
            model_name='imageflag',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved', False), ('spc_image__isnull', False)), fields=('flagged_by', 'spc_image'), name='uniq_open_flag_by_user_on_spc'),
        ),
        migrations.AddConstraint(
            model_name='imageflag',
            constraint=models.UniqueConstraint(condition=models.Q(('hyb_image__isnull', False), ('resolved', False)), fields=('flagged_by', 'hyb_image'), name='uniq_open_flag_by_user_on_hyb'),
        ),
    ]
