# Generated by Django 4.2.14 on 2025-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0025_imageflag_remove_spcimghistory_pid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageflag',
            old_name='reason',
            new_name='description',
        ),
        migrations.AddField(
            model_name='imageflag',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='imageflag',
            name='title',
            field=models.CharField(choices=[('not_approved', 'Not approved'), ('fraud', 'Fraud'), ('misidentified', 'Misidentified'), ('other', 'Other')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
