# Generated by Django 4.2.14 on 2025-10-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0026_rename_reason_imageflag_description_imageflag_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageflag',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='imageflag',
            old_name='species',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='imageflag',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='imageflag',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
