# Generated by Django 4.2.14 on 2025-10-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0027_rename_created_at_imageflag_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageflag',
            name='title',
            field=models.CharField(choices=[('unapproved', 'Not approved'), ('fraud', 'Fraud'), ('misidentified', 'Misidentified'), ('other', 'Other')], max_length=20),
        ),
    ]
