# Generated by Django 4.2.14 on 2025-11-13 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orchidaceae', '0029_spcimghistory_hybimghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimghistory',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='spcimghistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='imageflag',
            name='username',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flagusername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HybImgHistory',
        ),
        migrations.DeleteModel(
            name='SpcImgHistory',
        ),
    ]
