# Generated by Django 4.2.14 on 2025-11-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidaceae', '0030_remove_spcimghistory_pid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageflag',
            name='username',
        ),
    ]
