# Generated by Django 3.2.15 on 2024-03-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist', models.CharField(db_column='artist', default='', max_length=50, primary_key=True, serialize=False)),
                ('statement', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('url', models.URLField(null=True)),
                ('profile_pic_path', models.ImageField(blank=True, null=True, upload_to='images/user_profile/')),
                ('media', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(db_column='city', max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(db_column='genre', default='', max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('medium', models.CharField(db_column='medium', default='', max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('url', models.URLField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(db_column='city', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='galcity', to='gallery.city')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('support', models.CharField(blank=True, max_length=200)),
                ('hashtag', models.CharField(blank=True, max_length=200)),
                ('style', models.CharField(blank=True, max_length=200)),
                ('price', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('NFS', 'not for sale'), ('AV', 'available'), ('PUR', 'price upon request')], default='', max_length=20)),
                ('source_url', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=5)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(upload_to='gallery/artworks/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('artist', models.ForeignKey(db_column='artist', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artistwork', to='gallery.artist')),
                ('genre', models.ForeignKey(db_column='genre', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artistgenre', to='gallery.genre')),
                ('medium', models.ForeignKey(db_column='medium', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artistmedium', to='gallery.medium')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='city',
            field=models.ForeignKey(db_column='city', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artcity', to='gallery.city'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
