# Generated by Django 3.2.15 on 2023-04-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20230429_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
