# Generated by Django 3.2.15 on 2023-06-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_name_artist_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist',
            field=models.CharField(db_column='artist', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.CharField(max_length=200),
        ),
    ]
