# Generated by Django 3.2.15 on 2023-06-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20230620_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist',
            field=models.CharField(db_column='artist', default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
