# Generated by Django 3.2.15 on 2023-06-20 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20230620_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(db_column='artist', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='artistwork', to='gallery.artist'),
        ),
    ]
