# Generated by Django 3.2.15 on 2023-07-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_artwork_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='rank',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=5),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='hashtag',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image_file',
            field=models.ImageField(upload_to='gallery/artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
