# Generated by Django 3.2.15 on 2023-07-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20230712_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
