# Generated by Django 3.2.15 on 2023-07-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20230712_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_file',
            field=models.ImageField(default=None, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
