# Generated by Django 3.2.15 on 2023-07-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20230713_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
