# Generated by Django 3.2.15 on 2023-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_artwork_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
