# Generated by Django 3.2.15 on 2023-07-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20230713_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='source_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
