# Generated by Django 3.2.15 on 2023-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_artwork_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
