# Generated by Django 3.2.15 on 2023-07-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_artwork_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='support',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='source_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
