# Generated by Django 3.2.15 on 2023-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20230714_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='support',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
