# Generated by Django 3.2.15 on 2023-07-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_alter_artwork_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/artist/'),
        ),
    ]
