# Generated by Django 3.2.15 on 2023-07-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_alter_artist_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image_file',
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_pic_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_profile/'),
        ),
    ]
