# Generated by Django 4.2.14 on 2024-09-09 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binomial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(blank=True, max_length=200, null=True)),
                ('binomial', models.CharField(blank=True, max_length=200, null=True)),
                ('binomial_search', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.CharField(blank=True, max_length=200, null=True)),
                ('species_search', models.CharField(blank=True, max_length=200, null=True)),
                ('application', models.CharField(choices=[('animalia', 'animalia'), ('aves', 'aves'), ('fungi', 'fungi'), ('other', 'other'), ('orchidaceae', 'orchidaceae')], default='', max_length=20)),
                ('level', models.CharField(choices=[('Family', 'Family'), ('Genus', 'Genus'), ('Accepted', 'Accepted')], default='', max_length=20)),
                ('taxon_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=500, null=True)),
                ('common_name_search', models.CharField(blank=True, max_length=500, null=True)),
                ('application', models.CharField(choices=[('animalia', 'animalia'), ('aves', 'aves'), ('fungi', 'fungi'), ('other', 'other'), ('orchidaceae', 'orchidaceae')], default='', max_length=20)),
                ('level', models.CharField(choices=[('Family', 'Family'), ('Genus', 'Genus'), ('Accepted', 'Accepted')], default='', max_length=20)),
                ('taxon_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('dist_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('dist_num', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('orig_code', models.CharField(blank=True, max_length=100, null=True)),
                ('uncertainty', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('source', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_home', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('citing', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('collaboration', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family', models.CharField(db_column='family', default='', max_length=50, primary_key=True, serialize=False)),
                ('orig_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('application', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('common_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.CharField(max_length=20, null=True)),
                ('clss', models.CharField(max_length=20, null=True)),
                ('kingdom', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('registered', 'registered'), ('nonregistered', 'nonregistered'), ('unplaced', 'unplaced'), ('published', 'published'), ('trade', 'trade')], default='', max_length=20)),
                ('source', models.CharField(max_length=20, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['family'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('continent', models.ForeignKey(blank=True, db_column='continent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Subfamily',
            fields=[
                ('subfamily', models.CharField(db_column='subfamily', default='', max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('registered', 'registered'), ('nonregistered', 'nonregistered'), ('unplaced', 'unplaced'), ('published', 'published'), ('trade', 'trade')], default='', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_genus', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('family', models.ForeignKey(blank=True, db_column='family', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.family')),
            ],
            options={
                'ordering': ['subfamily'],
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.BigIntegerField(db_column='pid')),
                ('credit_to', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.CharField(blank=True, max_length=200, null=True)),
                ('variation', models.CharField(blank=True, max_length=50, null=True)),
                ('forma', models.CharField(blank=True, max_length=50, null=True)),
                ('originator', models.CharField(blank=True, max_length=50, null=True)),
                ('text_data', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('certainty', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0)),
                ('image_file_path', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_file', models.CharField(blank=True, max_length=100, null=True)),
                ('is_private', models.BooleanField(default=False, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('compressed', models.BooleanField(default=False, null=True)),
                ('block_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(blank=True, db_column='author', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cocauthor', to='accounts.photographer')),
                ('family', models.ForeignKey(db_column='family', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spcomfamily', to='common.family')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cocuser_id1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('tribe', models.CharField(db_column='tribe', default='', max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_genus', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('family', models.ForeignKey(db_column='family', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='common.family')),
                ('subfamily', models.ForeignKey(db_column='subfamily', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.subfamily')),
            ],
            options={
                'ordering': ['tribe'],
            },
        ),
        migrations.CreateModel(
            name='Subtribe',
            fields=[
                ('subtribe', models.CharField(db_column='subtribe', default='', max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_genus', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('family', models.ForeignKey(db_column='family', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='common.family')),
                ('subfamily', models.ForeignKey(db_column='subfamily', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.subfamily')),
                ('tribe', models.ForeignKey(db_column='tribe', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.tribe')),
            ],
            options={
                'ordering': ['subtribe'],
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('continent', models.ForeignKey(blank=True, db_column='continent', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.continent')),
                ('region', models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.region')),
            ],
        ),
        migrations.CreateModel(
            name='SpellChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_spelling', models.CharField(max_length=255)),
                ('common_misspelling', models.CharField(max_length=255)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_corrected', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('correct_spelling', 'common_misspelling')},
            },
        ),
        migrations.CreateModel(
            name='LocalRegion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('continent_name', models.CharField(max_length=100, null=True)),
                ('region_name', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('subregion', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('continent', models.ForeignKey(blank=True, db_column='continent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.continent')),
                ('region', models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.region')),
                ('subregion_code', models.ForeignKey(blank=True, db_column='subregion_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.subregion')),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.geolocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
