# Generated by Django 3.2.5 on 2022-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('source', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_home', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
