# Generated by Django 3.2.15 on 2024-05-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_commonname'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonname',
            name='common_name_search',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commonname',
            name='common_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
