# Generated by Django 3.2.15 on 2024-06-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20240507_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binomial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binomial', models.CharField(blank=True, max_length=200, null=True)),
                ('binomial_search', models.CharField(blank=True, max_length=200, null=True)),
                ('application', models.CharField(choices=[('animalia', 'animalia'), ('aves', 'aves'), ('fungi', 'fungi'), ('other', 'other'), ('orchidaceae', 'orchidaceae')], default='', max_length=20)),
                ('level', models.CharField(choices=[('Family', 'Family'), ('Genus', 'Genus'), ('Accepted', 'Accepted')], default='', max_length=20)),
                ('taxon_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
