# Generated by Django 3.2.5 on 2022-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220210_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='citing',
            field=models.TextField(null=True),
        ),
    ]
