# Generated by Django 3.2.5 on 2022-02-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_datasource_citing'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='collaboration',
            field=models.TextField(null=True),
        ),
    ]
