# Generated by Django 3.2.15 on 2024-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_binomial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binomial',
            name='genus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='binomial',
            name='species',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='binomial',
            name='species_search',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
