# Generated by Django 3.2.15 on 2024-06-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20240605_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_spelling', models.CharField(max_length=255)),
                ('common_misspelling', models.CharField(max_length=255)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_corrected', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('correct_spelling', 'common_misspelling')},
            },
        ),
    ]
