# Generated by Django 3.2.2 on 2021-06-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bromeliaceae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='common_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='common_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
