# Generated by Django 3.0.9 on 2021-01-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_family_active'),
        ('bromeliaceae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(default=10, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=10)),
                ('dist_code', models.CharField(max_length=10, null=True)),
                ('localregion_code', models.CharField(max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('localregion_id', models.ForeignKey(blank=True, db_column='localregion_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='natlocalregion_id', to='core.LocalRegion')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, related_name='dist_pid', to='bromeliaceae.Species')),
                ('region_id', models.ForeignKey(db_column='region_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='natregion_id', to='core.Region')),
                ('subregion_code', models.ForeignKey(db_column='subregion_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='natsubregion_id', to='core.SubRegion')),
            ],
            options={
                'unique_together': {('pid', 'region_id', 'subregion_code', 'localregion_id')},
            },
        ),
    ]
