# Generated by Django 3.0.9 on 2021-01-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_family_active'),
        ('bromeliaceae', '0002_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybimages',
            name='family',
            field=models.ForeignKey(db_column='family', default='Bromeliaceae', on_delete=django.db.models.deletion.DO_NOTHING, related_name='brohybfamily', to='core.Family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spcimages',
            name='family',
            field=models.ForeignKey(db_column='family', default='Bromeliaceae', on_delete=django.db.models.deletion.DO_NOTHING, related_name='brospcfamily', to='core.Family'),
            preserve_default=False,
        ),
    ]
