# Generated by Django 3.0.9 on 2021-01-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bromeliaceae', '0003_auto_20210108_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spcimages',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='natpid', to='bromeliaceae.Species'),
        ),
    ]
