# Generated by Django 3.0.9 on 2021-01-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bromeliaceae', '0004_auto_20210108_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HybImages',
        ),
    ]
