# Generated by Django 3.0.9 on 2021-01-08 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bromeliaceae', '0005_delete_hybimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='spcimages',
            name='genus',
            field=models.ForeignKey(blank=True, db_column='genus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='brogenus', to='bromeliaceae.Genus'),
        ),
    ]
