# Generated by Django 3.0.9 on 2021-01-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bromeliaceae', '0006_spcimages_genus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spcimages',
            name='genus',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
