# Generated by Django 3.0.9 on 2021-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bromeliaceae', '0007_auto_20210108_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='pollen_species',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='seed_species',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
