# Generated by Django 3.1.6 on 2021-04-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bromeliaceae', '0017_species_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='family',
        ),
    ]
