# Generated by Django 3.1 on 2021-04-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bromeliaceae', '0022_auto_20210426_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='is_carnivorous',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='genus',
            name='is_extinct',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
