# Generated by Django 3.0.9 on 2020-10-10 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(default=None, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('credited_name', models.CharField(max_length=255, null=True)),
                ('specialty', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('dist_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('dist_num', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('orig_code', models.CharField(blank=True, max_length=100, null=True)),
                ('uncertainty', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('tier', models.IntegerField(primary_key=True, serialize=False)),
                ('max_upload', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('author_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('web', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='TBD', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expertise', models.CharField(max_length=500, null=True)),
                ('user_id', models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('displayname', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('logo', models.CharField(blank=True, max_length=50)),
                ('banner', models.CharField(blank=True, max_length=50)),
                ('banner_color', models.CharField(blank=True, max_length=50)),
                ('affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('web', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='TBD', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('information', models.TextField(null=True)),
                ('author', models.ForeignKey(blank=True, db_column='author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Photographer')),
                ('user_id', models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('payment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(db_column='tier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tier'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('confirm_email', models.CharField(blank=True, max_length=100)),
                ('photo_credit_name', models.CharField(blank=True, max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=500, null=True)),
                ('portfolio_site', models.URLField(blank=True, max_length=500)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('profile_pic_url', models.URLField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Country')),
                ('current_credit_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Photographer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
