# Generated by Django 3.0.9 on 2020-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='web',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
