# Generated by Django 4.2.14 on 2024-09-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
