# Generated by Django 3.2.5 on 2021-12-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
