# Generated by Django 3.2.5 on 2022-01-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211219_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
