# Generated by Django 3.2.15 on 2022-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_sponsor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='short_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
