# Generated by Django 3.2.15 on 2022-11-09 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sponsor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='specialty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
