# Generated by Django 3.2.15 on 2022-11-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221109_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='user_id',
            new_name='user',
        ),
    ]
