# Generated by Django 3.2.2 on 2021-06-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cactaceae', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='common_name',
        ),
    ]
