# Generated by Django 3.2.2 on 2021-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactaceae', '0002_remove_genus_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='common_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
