# Generated by Django 3.1.6 on 2021-03-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cactaceae', '0006_auto_20210328_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='scientific_name',
            new_name='binomial',
        ),
    ]
