# Generated by Django 3.1.6 on 2021-04-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210329_1547'),
        ('cactaceae', '0009_genusrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='dist_code',
        ),
        migrations.AddField(
            model_name='distribution',
            name='continent_id',
            field=models.ForeignKey(blank=True, db_column='continent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cac_continent_id', to='core.continent'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='distribution',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='orig_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
