# Generated by Django 3.2.15 on 2022-12-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='is_succulent',
            new_name='is_migratory',
        ),
    ]
