# Generated by Django 3.2.15 on 2024-03-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE aves_accepted ADD FULLTEXT(binomial, common_name)',
            reverse_sql='ALTER TABLE aves_accepted DROP INDEX accepted_content_fulltext'
        ),
    ]
