# Generated by Django 4.2.14 on 2024-09-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('change_frequency', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=50)),
                ('priority', models.FloatField(blank=True, default=0.5, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
