# Generated by Django 4.2.14 on 2024-08-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemapentry',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
