# Generated by Django 3.2.15 on 2024-03-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalia', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE animalia_accepted ADD FULLTEXT(binomial, common_name)',
            reverse_sql='ALTER TABLE animalia_accepted DROP INDEX accepted_content_fulltext'
        ),
    ]
