# Generated by Django 4.2.14 on 2024-12-11 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimages',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='download_date',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='species',
        ),
        migrations.RemoveField(
            model_name='species',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='species',
            name='notepad',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_ancestor',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_descendant',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_dir_descendant',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_image',
        ),
        migrations.RemoveField(
            model_name='species',
            name='num_species_ancestor',
        ),
        migrations.RemoveField(
            model_name='species',
            name='physiology',
        ),
        migrations.RemoveField(
            model_name='species',
            name='url',
        ),
        migrations.RemoveField(
            model_name='species',
            name='url_name',
        ),
        migrations.AddField(
            model_name='hybrid',
            name='pollen_accid',
            field=models.ForeignKey(blank=True, db_column='pollen_accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anipollen_accid', to='animalia.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='seed_accid',
            field=models.ForeignKey(blank=True, db_column='seed_accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aniseed_accid', to='animalia.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='spcimages',
            name='accid',
            field=models.ForeignKey(blank=True, db_column='accid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aniimgaccid', to='animalia.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='spcimages',
            name='base_pid',
            field=models.ForeignKey(blank=True, db_column='base_pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aniimgbase_pid', to='animalia.species', verbose_name='grex'),
        ),
        migrations.AddField(
            model_name='species',
            name='accid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='base_pid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
