# Generated by Django 3.2.15 on 2024-04-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalia', '0002_auto_20240305_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='cit_status',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='species',
            name='cit_status',
        ),
        migrations.RemoveField(
            model_name='species',
            name='citation',
        ),
    ]
