# Generated by Django 4.2.14 on 2025-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalia', '0005_alter_speciesstat_num_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='common_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
