# Generated by Django 3.2.15 on 2024-05-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalia', '0006_uploadfile_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='family',
        ),
    ]
