# Generated by Django 3.2.15 on 2024-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalia', '0007_remove_uploadfile_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='binomial',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
