# Generated by Django 3.0.9 on 2021-01-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactaceae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='full_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
