# Generated by Django 3.0.9 on 2021-01-09 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_family_active'),
        ('cactaceae', '0002_distribution_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spcimages',
            name='family',
            field=models.ForeignKey(db_column='family', default='Cactaceae', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cacspcfamily', to='core.Family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spcimages',
            name='genus',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
