# Generated by Django 3.1.6 on 2021-03-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cactaceae', '0005_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybimages',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='hybimages',
            name='author',
        ),
        migrations.RemoveField(
            model_name='hybimages',
            name='gen',
        ),
        migrations.RemoveField(
            model_name='hybimages',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='hybimages',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='continent_id',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='spcimages',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cacpid', to='cactaceae.species'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='pid',
            field=models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cacpid1', to='cactaceae.species'),
        ),
        migrations.DeleteModel(
            name='GenusRelation',
        ),
        migrations.DeleteModel(
            name='HybImages',
        ),
    ]
