# Generated by Django 3.1.6 on 2021-04-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cactaceae', '0008_ancestordescendant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenusRelation',
            fields=[
                ('gen', models.OneToOneField(db_column='gen', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cactaceae.genus')),
                ('genus', models.CharField(default='', max_length=50)),
                ('parentlist', models.CharField(max_length=500, null=True)),
                ('formula', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
