# Generated by Django 3.1.6 on 2021-04-17 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210329_1547'),
        ('cactaceae', '0011_genus_binomial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.ForeignKey(db_column='family', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spcafamily', to='core.family'),
        ),
    ]
