# Generated by Django 4.2.14 on 2024-09-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenusStat',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='genusstat', serialize=False, to='fungi.genus')),
                ('num_species', models.IntegerField(default=0, null=True)),
                ('num_species_synonym', models.IntegerField(default=0, null=True)),
                ('num_species_total', models.IntegerField(default=0, null=True)),
                ('num_hybrid', models.IntegerField(default=0, null=True)),
                ('num_hybrid_synonym', models.IntegerField(default=0, null=True)),
                ('num_hybrid_total', models.IntegerField(default=0, null=True)),
                ('num_synonym', models.IntegerField(default=0, null=True)),
                ('num_spcimage', models.IntegerField(default=0, null=True)),
                ('num_spc_with_image', models.IntegerField(default=0, null=True)),
                ('pct_spc_with_image', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('num_hybimage', models.IntegerField(default=0, null=True)),
                ('num_hyb_with_image', models.IntegerField(default=0, null=True)),
                ('pct_hyb_with_image', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesStat',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='speciesstat', serialize=False, to='fungi.species')),
                ('num_image', models.IntegerField(blank=True)),
                ('num_ancestor', models.IntegerField(blank=True, null=True)),
                ('num_species_ancestor', models.IntegerField(blank=True, null=True)),
                ('num_descendant', models.IntegerField(blank=True, null=True)),
                ('num_dir_descendant', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
