# Generated by Django 3.2.15 on 2022-11-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimages',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='spid',
        ),
    ]
