# Generated by Django 3.2.15 on 2022-11-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0002_auto_20221127_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimages',
            name='gen',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='spcimages',
            name='zoom',
        ),
        migrations.AddField(
            model_name='spcimages',
            name='binomial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
