# Generated by Django 4.2.14 on 2025-05-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0002_hybrid_pollen_accid_hybrid_seed_accid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimages',
            name='image_file_path',
        ),
    ]
