# Generated by Django 4.2.14 on 2025-05-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0003_remove_spcimages_image_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genusstat',
            name='num_hyb_with_image',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='num_hybimage',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='num_hybrid',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='num_hybrid_synonym',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='num_hybrid_total',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='num_spc_with_image',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='num_species_synonym',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='num_species_total',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='num_synonym',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='pct_hyb_with_image',
        ),
        migrations.RemoveField(
            model_name='genusstat',
            name='pct_spc_with_image',
        ),
        migrations.RemoveField(
            model_name='speciesstat',
            name='num_ancestor',
        ),
        migrations.RemoveField(
            model_name='speciesstat',
            name='num_descendant',
        ),
        migrations.RemoveField(
            model_name='speciesstat',
            name='num_dir_descendant',
        ),
        migrations.RemoveField(
            model_name='speciesstat',
            name='num_species_ancestor',
        ),
        migrations.AddField(
            model_name='genusstat',
            name='best_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='genusstat',
            name='best_image_pid',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='speciesstat',
            name='best_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
