# Generated by Django 3.2.15 on 2022-11-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0004_auto_20221127_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcimages',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='is_private',
        ),
    ]
