# Generated by Django 3.2.15 on 2022-11-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0005_auto_20221127_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='spcimages',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
