# Generated by Django 3.2.15 on 2022-12-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0007_remove_uploadfile_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='binomial',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='binomial',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
