# Generated by Django 3.2.15 on 2022-12-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0008_auto_20221201_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='history',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='infraspe',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='infraspr',
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='species',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='history',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='infraspe',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='infraspr',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='species',
        ),
    ]
