# Generated by Django 3.2.15 on 2023-03-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0011_rename_is_carnivorous_species_is_edible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='dist',
            field=models.ForeignKey(db_column='dist', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='fungi.location'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='pid',
            field=models.ForeignKey(db_column='pid', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fundist_pid', to='fungi.species'),
        ),
    ]
